sudo: 'required'

go:
    - 1.8
    - 1.9
    - "1.10"


jobs:
  include:
    - stage: test
      script: make deps check test build
    - stage: build docker image
      services:
      - 'docker'
      before_install: './.travis/main.sh'
      script: make docker-build
    - stage: deploy
      if: branch = master
      services:
      - 'docker'
      before_install: './.travis/main.sh'
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - make docker-build
      - make docker-push
