
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "v1.0.4"

[[constraint]]
  name = "github.com/bwmarrin/discordgo"
  version = "v0.18.0"

[[constraint]]
  name = "github.com/mattn/go-colorable"
  version = "v0.0.9"

[[constraint]]
  name = "github.com/rylio/ytdl"
  version = "v0.5.1"

[[constraint]]
  name = "github.com/jonas747/dca"
  revision = "01f9985f4a26c29c2b4f5a7c133395e1aa6fffca"

[[override]]
  name = "github.com/jonas747/ogg"
  revision = "b4f6f4cf3757a3bf88eae9222045b99b9d76d8ca"
